# optional parameter, defaults to sonarcloud.io
sonar.host.url=https://sonarcloud.io
# required parameters
sonar.organization=govuk-one-login
sonar.projectKey=govuk-one-login_relying-party-configuration
sonar.projectName=relying-party-configuration
# Project specific analysis parameters, will vary depending on the application
sonar.exclusions=**/*.java
sonar.sources=.