name: Deploy API Dev

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  deploy-api-dev:
    uses: ./.github/workflows/deploy-api.yml
    secrets:
      GH_ACTIONS_ROLE_ARN: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
      ARTIFACT_BUCKET_NAME: ${{ secrets.DEV_ARTIFACT_BUCKET_NAME }}
      SIGNING_PROFILE_NAME: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      ECR_REPOSITORY: ${{ secrets.DEV_TEST_ECR_REPOSITORY }}
