name: Pre-merge checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  style-checks:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Run lint + prettier
        run: npm run lint
      - name: Set up tflint
        uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33
      - name: Lint Terraform
        run: npm run tflint
  terraform-checks:
    name: Terraform Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Format Check
        working-directory: infra
        run: terraform fmt -check -recursive
      - name: Terraform Validate
        working-directory: infra
        run: |
          terraform init -input=false -backend=false
          terraform validate
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure Docker for ARM
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      - name: Start and run tests
        run: npm run start:local & (until curl --silent 127.0.0.1:3000/authorize; do sleep 1; done && npm run test:unit; npm run test:integration; exit 0)
  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11.2'
      - name: Detect secrets
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: "detect-secrets --all-files"
# TODO: add cfnlint, and SAM validate
