name: Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  merge_group:

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yml

  sonarcloud:
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  terraform-checks:
    uses: ./.github/workflows/terraform-checks.yml

  checkov:
    uses: ./.github/workflows/checkov.yml

  validation:
    uses: ./.github/workflows/validation.yml
    secrets:
      SAM_VALIDATE_ROLE_ARN: ${{ secrets.DEV_SAM_VALIDATE_ROLE_ARN }}
