name: Validation

on:
  workflow_call:
    secrets:
      SAM_VALIDATE_ROLE_ARN:
        required: true

jobs:
  style-checks:
    name: Validation Checks
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Check ESLint and Prettier
        run: npm run lint

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93

      - name: Lint Terraform
        run: npm run tflint

      - name: Setup SAM
        if: github.actor != 'dependabot[bot]'
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          use-installer: true

      - name: Set up AWS credentials
        if: github.actor != 'dependabot[bot]'
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.SAM_VALIDATE_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Run SAM validate + cfnlint
        if: github.actor != 'dependabot[bot]'
        run: sam validate -t template.yml --region eu-west-2 --lint

  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.11.2"

      - name: Run detect-secrets
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: "detect-secrets --all-files"
